
//movies
const movies = [
  {
    film_id: '1',
    title: 'Borrowers Bedazzled',
    description: 'A Brilliant Epistle of a Teacher And a Sumo Wrestler who must Defeat a Man in An Abandoned Fun House',
    release_year: 2006,
    language_id: 1,
    rental_duration: 7,
    rental_rate: '0.99',
    length: 63,
    replacement_cost: '22.99',
    rating: 'G',
    last_update: '2013-05-26T12:50:58.951Z',
    special_features: [ 'Commentaries', 'Deleted Scenes', 'Behind the Scenes' ],
    fulltext: "'abandon':20 'bedazzl':2 'borrow':1 'brilliant':4 'defeat':15 'epistl':5 'fun':21 'hous':22 'man':17 'must':14 'sumo':11 'teacher':8 'wrestler':12"
  },
  {
    film_id: '2',
    title: 'Boulevard Mob',
    description: 'A Fateful Epistle of a Moose And a Monkey who must Confront a Lumberjack in Ancient China',
    release_year: 2006,
    language_id: 1,
    rental_duration: 3,
    rental_rate: '0.99',
    length: 63,
    replacement_cost: '11.99',
    rating: 'R',
    last_update: '2013-05-26T12:50:58.951Z',
    special_features: [ 'Trailers' ],
    fulltext: "'ancient':18 'boulevard':1 'china':19 'confront':14 'epistl':5 'fate':4 'lumberjack':16 'mob':2 'monkey':11 'moos':8 'must':13"
  },
  {
    film_id: '3',
    title: 'Bound Cheaper',
    description: 'A Thrilling Panorama of a Database Administrator And a Astronaut who must Challenge a Lumberjack in A Baloon',
    release_year: 2006,
    language_id: 1,
    rental_duration: 5,
    rental_rate: '0.99',
    length: 98,
    replacement_cost: '17.99',
    rating: 'PG',
    last_update: '2013-05-26T12:50:58.951Z',
    special_features: [ 'Behind the Scenes' ],
    fulltext: "'administr':9 'astronaut':12 'baloon':20 'bound':1 'challeng':15 'cheaper':2 'databas':8 'lumberjack':17 'must':14 'panorama':5 'thrill':4"
  },
  {
    film_id: '4',
    title: 'Bowfinger Gables',
    description: 'A Fast-Paced Yarn of a Waitress And a Composer who must Outgun a Dentist in California',
    release_year: 2006,
    language_id: 1,
    rental_duration: 7,
    rental_rate: '4.99',
    length: 72,
    replacement_cost: '19.99',
    rating: 'NC-17',
    last_update: '2013-05-26T12:50:58.951Z',
    special_features: [ 'Trailers', 'Deleted Scenes' ],
    fulltext: "'bowfing':1 'california':20 'compos':13 'dentist':18 'fast':5 'fast-pac':4 'gabl':2 'must':15 'outgun':16 'pace':6 'waitress':10 'yarn':7"
  },
  {
    film_id: '5',
    title: 'Brannigan Sunrise',
    description: 'A Amazing Epistle of a Moose And a Crocodile who must Outrace a Dog in Berlin',
    release_year: 2006,
    language_id: 1,
    rental_duration: 4,
    rental_rate: '4.99',
    length: 121,
    replacement_cost: '27.99',
    rating: 'PG',
    last_update: '2013-05-26T12:50:58.951Z',
    special_features: [ 'Trailers' ],
    fulltext: "'amaz':4 'berlin':18 'brannigan':1 'crocodil':11 'dog':16 'epistl':5 'moos':8 'must':13 'outrac':14 'sunris':2"
  },
  {
    film_id: '6',
    title: 'Braveheart Human',
    description: 'A Insightful Story of a Dog And a Pastry Chef who must Battle a Girl in Berlin',
    release_year: 2006,
    language_id: 1,
    rental_duration: 7,
    rental_rate: '2.99',
    length: 176,
    replacement_cost: '14.99',
    rating: 'PG-13',
    last_update: '2013-05-26T12:50:58.951Z',
    special_features: [ 'Trailers', 'Deleted Scenes' ],
    fulltext: "'battl':15 'berlin':19 'braveheart':1 'chef':12 'dog':8 'girl':17 'human':2 'insight':4 'must':14 'pastri':11 'stori':5"
  },
];
  
  module.exports = {movies};